/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Datos.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Timestamp;
import java.util.Date;




/**
 *
 * @author Eduardo
 */
public class GUILogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private String usuario = "";
    private String contrasena = "";
    private int perfil = 0;
    Conexion conexion = new Conexion();
    Connection con = conexion.getConnection();
    Statement st;
    String sql="";
    ResultSet rs;
    public GUILogin() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtPassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login - Torneo");
        setMaximumSize(new java.awt.Dimension(460, 280));
        setMinimumSize(new java.awt.Dimension(460, 280));
        setPreferredSize(new java.awt.Dimension(460, 280));
        getContentPane().setLayout(null);

        jPanel1.setMaximumSize(new java.awt.Dimension(460, 280));
        jPanel1.setLayout(null);

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario);
        lblUsuario.setBounds(140, 70, 50, 14);

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPassword.setText("Password: ");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(130, 110, 70, 14);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAceptar);
        btnAceptar.setBounds(130, 200, 71, 23);

        btnCancelar.setText("Cancelar");
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(260, 200, 75, 23);
        jPanel1.add(txtPassword);
        txtPassword.setBounds(200, 100, 110, 30);
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(200, 60, 111, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/imagenes/versus.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 450, 260);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 460, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        // TODO add your handling code here:
        buscarUsuario(txtUsuario.getText(), txtPassword.getText());
        if (txtUsuario.getText().equals(usuario) && txtPassword.getText().equals(contrasena)) {
            switch (perfil) {
                case 1: 
                    if (primeravez() == true) {
                        GUIACT guiact = new GUIACT();
                        this.dispose();
                        guiact.setVisible(true);
                        actualizaFecha();
                    }else{
                        try {
                            actualizaFecha();
                            GUIPrincipalAdm guiPA = new GUIPrincipalAdm();
                            this.dispose();
                            guiPA.setVisible(true);
                        } catch (Exception e) {
                            System.out.println("Error al ingresar al panel de administrador: \n"+e.getMessage());
                        }
                    }
                    break;
                case 2:
                    try {
                        actualizaFecha();
                        GUIPrincipalStaff guiPS = new GUIPrincipalStaff();
                        this.dispose();
                        guiPS.setVisible(true);
                    } catch (Exception e) {
                        System.out.println("Error al ingresar al sistema: \n"+e.getMessage());
                    }
                    
                    break;
                case 3:
                    try {
                        actualizaFecha();
                        GUIPrincipalCapitan guiPC = new GUIPrincipalCapitan();
                        this.dispose();
                        guiPC.setVisible(true);
                    } catch (Exception e) {
                        System.out.println("Error al ingresar al sistema: \n"+e.getMessage());
                    }
                    break;
                default:
                    throw new AssertionError();
            }
        }else{
            System.out.println("Error de credenciales.");
            System.out.println("Clave: "+contrasena);
        }               
    }//GEN-LAST:event_btnAceptarActionPerformed
     public void buscarUsuario(String usuarioW,String contrasenaW){ 
         try {
             st = con.createStatement();
             sql="SELECT * FROM USUARIO WHERE (usuario='"+usuarioW+"' and contrasena='"+contrasenaW+"')";
             rs = st.executeQuery(sql);
             while (rs.next()) {
                 usuario = rs.getString(2);
                 contrasena = rs.getString(3);
                 perfil = rs.getInt(4);
             }
             st.close();
             System.out.println("Buscando al usuario: "+usuario);
         } catch (Exception e) {
             System.out.println("Error al buscar el usuario: "+ usuario+ "\nError: "+e.getMessage());
         }
     }
     public boolean primeravez(){
         boolean valida = false;
             try {
                 String fecha = "0000-00-00 00:00:00.000000";
                 st = con.createStatement();
                 sql = "SELECT * FROM USUARIO WHERE (usuario = '"+usuario+"' and fechaLogin = '"+fecha+"' )";
                 rs = st.executeQuery(sql);
                 while (rs.next()) {
                     valida = true;
                 }
             } catch (Exception e) {
                 valida = false;
             }         
         return valida;
     }
     
     public void actualizaFecha(){
         Timestamp fechaux;
         Date fecha = new Date();
         fechaux = new Timestamp(fecha.getTime());
         try {
             st = con.createStatement();
             sql = "UPDATE usuario set fechaLogin='"+fechaux+"' where(usuario='"+txtUsuario.getText()+"')";
             st.executeUpdate(sql);
             st.close();
         } catch (Exception e) {
             System.out.println("Error al actualizar la fecha de login :\n"+e.getMessage());
         }
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUILogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               GUILogin gui = new GUILogin();
                gui.setSize(460, 280);
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
