/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Eduardo
 */
public class GUIPrincipalStaff extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipalStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPStaff = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mAgregarPart = new javax.swing.JMenu();
        mEquipos = new javax.swing.JMenu();
        miAñadirEquipo = new javax.swing.JMenuItem();
        miEditarEquipo = new javax.swing.JMenuItem();
        miEquipoAgregarSan = new javax.swing.JMenuItem();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STAFF - Nombre torneo");
        setMinimumSize(new java.awt.Dimension(584, 317));

        jLabel7.setText("Ultimo registro:");

        jLabel8.setText("Equipos participando:");

        jLabel9.setText("xxxx xxxxx xxxx");

        jLabel10.setText("Hay 10 equipos");

        jLabel11.setText("Participantes registrados:");

        jLabel12.setText("200 personas participando.");

        javax.swing.GroupLayout jPStaffLayout = new javax.swing.GroupLayout(jPStaff);
        jPStaff.setLayout(jPStaffLayout);
        jPStaffLayout.setHorizontalGroup(
            jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStaffLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addGroup(jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPStaffLayout.setVerticalGroup(
            jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPStaffLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        mAgregarPart.setText("Agregar Participante");
        mAgregarPart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mAgregarPartMouseClicked(evt);
            }
        });
        jMenuBar1.add(mAgregarPart);

        mEquipos.setText("Equipos");

        miAñadirEquipo.setText("Añadir equipo");
        miAñadirEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAñadirEquipoActionPerformed(evt);
            }
        });
        mEquipos.add(miAñadirEquipo);

        miEditarEquipo.setText("Editar equipo");
        miEditarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEditarEquipoActionPerformed(evt);
            }
        });
        mEquipos.add(miEditarEquipo);

        miEquipoAgregarSan.setText("Agregar sancion");
        miEquipoAgregarSan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEquipoAgregarSanActionPerformed(evt);
            }
        });
        mEquipos.add(miEquipoAgregarSan);

        jMenuBar1.add(mEquipos);

        mSalir.setText("Salir");
        mSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mAgregarPartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mAgregarPartMouseClicked
        // TODO add your handling code here:
        GUISAP guisap = new GUISAP();
        this.setVisible(false);
        guisap.setVisible(true);
    }//GEN-LAST:event_mAgregarPartMouseClicked

    private void mSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mSalirMouseClicked
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_mSalirMouseClicked

    private void miAñadirEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAñadirEquipoActionPerformed
        // TODO add your handling code here:
        GUISAE guisae = new GUISAE();
        this.setVisible(false);
        guisae.setVisible(true);
    }//GEN-LAST:event_miAñadirEquipoActionPerformed

    private void miEditarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEditarEquipoActionPerformed
        // TODO add your handling code here:
        GUISEE guisee = new GUISEE();
        this.setVisible(false);
        guisee.setVisible(true);
    }//GEN-LAST:event_miEditarEquipoActionPerformed

    private void miEquipoAgregarSanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEquipoAgregarSanActionPerformed
        // TODO add your handling code here:
        GUISAS  guisas = new GUISAS();
        this.setVisible(false);
        guisas.setVisible(true);
    }//GEN-LAST:event_miEquipoAgregarSanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                int perfil=1;
                GUIPrincipalStaff guip = new GUIPrincipalStaff();
                        guip.setSize(584, 317);
                        guip.setVisible(true);
                        if (perfil== 1) {
                           
                        }                        
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPStaff;
    private javax.swing.JMenu mAgregarPart;
    private javax.swing.JMenu mEquipos;
    private javax.swing.JMenu mSalir;
    private javax.swing.JMenuItem miAñadirEquipo;
    private javax.swing.JMenuItem miEditarEquipo;
    private javax.swing.JMenuItem miEquipoAgregarSan;
    // End of variables declaration//GEN-END:variables
}
